apiVersion: v1
kind: Service
metadata:
  name: {{ include "snyk-broker.brokerServiceName" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . }}
  {{- if .Values.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.brokerType }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.containerPort }}
  selector:
    {{- include "snyk-broker.selectorLabels" . | nindent 4 }}
